ingress:
  host: chart-example.local
  ingressClassName: nginx

gitRepository: laszlocph/demo-app
gitSha: xyz


volumes:
  - name: testing
    path: /deleteme
    hostPath:
      path: /deleteme
  - name: empty
    path: /deleteme2
    emptyDir: true
  - name: volume-name
    existingSecret: my-secret
    path: /randomPath/app.creds
    subPath: app.creds

vars:
  var1: value1
  var2: value2

probe:
  enabled: true
  settings:
    periodSeconds: 30

podSpec:
  hostNetwork: true
